/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import javax.swing.JOptionPane;

/**
 *
 * @author Sara Valentina
 */
public class InterfaceFormulario extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceFormulario
     */
    public InterfaceFormulario() {
        initComponents();
        panel2.setVisible(false);
        panel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioBtnCNormal = new javax.swing.JRadioButton();
        radioBtnCEspecial = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioBtnDeposito = new javax.swing.JRadioButton();
        radioBtnSaque = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        spinnerQuantia = new javax.swing.JSpinner();
        btntransacao = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblImpostoSaque = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNovoSaldo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Saldo: R$");

        lblSaldoInicial.setText("500");

        jLabel2.setText("Escolha uma opção:");

        buttonGroup1.add(radioBtnCNormal);
        radioBtnCNormal.setText("Cliente Normal");
        radioBtnCNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnCEspecial);
        radioBtnCEspecial.setText("Cliente Especial");

        jLabel3.setText("Escolha:");

        buttonGroup2.add(radioBtnDeposito);
        radioBtnDeposito.setText("Depósito");

        buttonGroup2.add(radioBtnSaque);
        radioBtnSaque.setText("Saque");

        jLabel5.setText("Quantia: R$");

        spinnerQuantia.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        btntransacao.setText("Efetuar transação");
        btntransacao.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btntransacaoComponentHidden(evt);
            }
        });
        btntransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransacaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Imposto por Saque: R$");

        lblImpostoSaque.setText("0");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblImpostoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblImpostoSaque))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setText("Novo Saldo: R$");

        lblNovoSaldo.setText("500");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblNovoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblNovoSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnDeposito)
                            .addComponent(radioBtnCEspecial)
                            .addComponent(radioBtnCNormal)
                            .addComponent(radioBtnSaque)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSaldoInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnSaque)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btntransacao)
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnCNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnCNormalActionPerformed

    private void btntransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransacaoActionPerformed
        // TODO add your handling code here:
     // btntransacao.setVisible(false);
        double quantia = (double) spinnerQuantia.getValue();
        double novoSaldo = Double.parseDouble(lblSaldoInicial.getText());
        if (radioBtnDeposito.isSelected()){ 
            double saldo = quantia + novoSaldo;
            lblNovoSaldo.setText(Double.toString(saldo));
            lblSaldoInicial.setText(Double.toString(saldo));
            panel1.setVisible(true);
        }
        
        if (radioBtnSaque.isSelected()){
            
              if (radioBtnCNormal.isSelected()){ 
                novoSaldo = Double.parseDouble(lblNovoSaldo.getText());
                double impAplicado = 0.30 * quantia;
                double saque = impAplicado + quantia;
                lblImpostoSaque.setText(Double.toString(impAplicado));
                
                if (saque > novoSaldo){
                    JOptionPane.showMessageDialog(null, "ERRO! Saque maior que Saldo disponivel.");
                } else {
                    double saldo;
                    saldo = novoSaldo - saque;
                    lblNovoSaldo.setText(Double.toString(saldo));
                    lblSaldoInicial.setText(Double.toString(saldo));
                    panel1.setVisible(true);
                    panel2.setVisible(true);
                    
                }    
                
              } 
               if (radioBtnCEspecial.isSelected()){ 
                novoSaldo = Double.parseDouble(lblNovoSaldo.getText());
                double impAplicado = 0.10 * quantia;
                double saque = impAplicado + quantia;
                lblImpostoSaque.setText(Double.toString(impAplicado));
                
                if (saque > novoSaldo){
                    JOptionPane.showMessageDialog(null, "ERRO! Saque maior que Saldo disponivel.");
                } else {
                    double saldo;
                    saldo = novoSaldo - saque;
                    lblNovoSaldo.setText(Double.toString(saldo));
                    lblSaldoInicial.setText(Double.toString(saldo));
                    panel1.setVisible(true);
                    panel2.setVisible(true);
                    
                }    
                
              } 
              
        }
        
    }//GEN-LAST:event_btntransacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btntransacaoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btntransacaoComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_btntransacaoComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceFormulario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntransacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblImpostoSaque;
    private javax.swing.JLabel lblNovoSaldo;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JRadioButton radioBtnCEspecial;
    private javax.swing.JRadioButton radioBtnCNormal;
    private javax.swing.JRadioButton radioBtnDeposito;
    private javax.swing.JRadioButton radioBtnSaque;
    private javax.swing.JSpinner spinnerQuantia;
    // End of variables declaration//GEN-END:variables
}
